### DISCUSSION TITLE
Deploy to Azure Container Instance Error: The requested resource is not available in the location 'eastus' at this moment

### DISCUSSION THREAD

**Discussion by fredqinms** [microsoft/vscode-docker#3625] [Q&A]
I am trying to use the Docker extension to publish the multi-container app to Azure Container Instances. I used `docker compose up` command and always got the following error for the resources. 

How can I set the resources to request in docker compose or azure? We only allow max 4gb and 16gb memory in the azure instances. 

`containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ServiceUnavailable" Message="The requested resource is not available in the location 'eastus' at this moment. Please retry with a different resource request or in another location. Resource requested: '7' CPU '6.1' GB memory 'Linux' OS"`

**Here is my docker compose file**

```
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
x-superset-image: &superset-image <xxxacr>.azurecr.io/superset:latest
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - docker:/app/docker
  - supersethome:/app/superset_home

version: "3.7"
services:
  redis:
    image: redis:latest
    container_name: superset-cache
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    env_file: docker/.env-non-dev
    image: postgres:10
    container_name: superset-db
    restart: unless-stopped
    volumes:
      - dbhome:/var/lib/postgresql/data

  superset:
    env_file: docker/.env-non-dev
    image: *superset-image
    container_name: superset-app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes   

  superset-init:
    image: *superset-image
    container_name: superset-init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env-non-dev
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

  superset-worker:
    image: *superset-image
    container_name: superset-worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

  superset-worker-beat:
    image: *superset-image
    container_name: superset-worker-beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes

volumes:
  docker:
    driver: azure_file
    driver_opts: 
      share_name: supersetshare
      storage_account_name: supersetstorageaccount
  supersethome:
    driver: azure_file
    driver_opts: 
      share_name: supersetshare
      storage_account_name: supersetstorageaccount
  dbhome:
    driver: azure_file
    driver_opts: 
      share_name: supersetshare
      storage_account_name: supersetstorageaccount
  redis:
    driver: azure_file
    driver_opts: 
      share_name: supersetshare
      storage_account_name: supersetstorageaccount

```
