### ISSUE TITLE
Visual Code - docker-compose Multi container application

### ISSUE THREAD

**Issue by henrymcbean** [microsoft/vscode-docker#2022]
How do I specify in the task.json where the package.json file is of the container I want to debug.  When I try to debug the node container I get error below.

ENOENT: no such file or directory, open 'c:\Users\Henry\Documents\React\complex\package.json'

The path to the file  is below

C:\Users\Henry\Documents\React\complex\client\package.json.

My docker-compose build and installs correctly and the application runs, have an error on one of the node api and need to debug.  I assume I am correct in thinking I should set where the file is in the task,json file.

**Comment by bwateratmsft** [comment]
Unfortunately we don't have true support yet for compose debugging with Node.js. That is being tracked in #1294.

However, it can still be done! I was able to set up an express app with debugging, with the following:

docker-compose.yml:
```yml
version: '3.4'

services:
  client:
    image: client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 3000
```

docker-compose.override.yml (created this one):
```yml
version: '3.4'

services:
  client:
    environment:
      - DEBUG=*
      - NODE_ENV=development
    ports:
      - 9229:9229
    entrypoint:
      node --inspect=0.0.0.0:9229 ./bin/www
```

client/Dockerfile (altered the paths to deal with context being one layer above the Dockerfile):
```dockerfile
FROM node:10.13-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY ["client/package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY client .
EXPOSE 3000
CMD npm start
```

.vscode/tasks.json:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Compose Up",
            "type": "shell",
            "command": "docker-compose up -d --build --force-recreate"
        }
    ]
}
```

.vscode/launch.json:
```json
{
    "configurations": [
        {
            "name": "Docker Node.js Launch",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "Compose Up",
            "platform": "node",
            "node": {
                "package": "${workspaceFolder}/client/package.json",
                "localRoot": "${workspaceFolder}/client"
            }
        }
    ]
}
```
