### ISSUE TITLE
Add Support for Blazor WebAssembly Projects

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-docker#2034]
1. Create a blazor webassembly project
2. Add Dockerfiles using extension
3. It adds files for Blazor Server project (I think)
4. It should add something like the following

nginx.conf - to the root of the project
```
events { }
   http {
      include mime.types;
      types {
         application/wasm wasm;
       }
     server {
        listen 80;
        index index.html;
        location / {
           root /var/www/web;
           try_files $uri $uri/ /index.html =404;
        }
     }
}
```

Dockerfile
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o output
FROM nginx:alpine
WORKDIR /var/www/web
COPY --from=build-env /app/output/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
```

docker-compose.yml - this should include a port map so it doesn't bind to port 80
```yml
# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  blazorapp:
    image: blazorapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
```

azsdke2e
