### ISSUE TITLE
Fail to execute the 'compose up' action

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2116]
**OS:** Win 10
**Build Version:** 20200629.7

**Repro Steps:**
1. Create a certs folder with command "mkdir %USERPROFILE%\certs".
2. Download mkcert and rename it to mkcert.exe.
3. Install the mkcert.exe with below command:
set CAROOT=%USERPROFILE%\certs\CARoot
cd %USERPROFILE%\certs
mkcert -install
4. Create a self-signed certification for SSL using the new CA certificate: mkcert 127.0.0.1.
5. Open the certs folder in VS Code and save both Dockerfile and docker-compose.yml to this folder.
Dockerfile content:
```
FROM registry
# Create a password file with username=testuser, password=testpassword
RUN mkdir /auth
RUN htpasswd -Bbn testuser testpassword > /auth/htpasswd
```
docker-compose.yml content:
```
version: '3.7'
services:
  registry:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5443:5443"
    volumes:
      - ".:/certs"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/127.0.0.1.pem
      REGISTRY_HTTP_TLS_KEY: /certs/127.0.0.1-key.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm  
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
```
6. Right click on docker-compose.yml -> Compose Up.

**Expect:**
Execute 'compose up' action successfully without any error.

**Actual:**
Fail to execute the 'compose up' action.
```
C:\Users\AzureTest\certs>docker-compose -f "docker-compose.yml.yml" up -d --build
Building registry
Step 1/3 : FROM registry
 ---> 2d4f4b5309b1
Step 2/3 : RUN mkdir /auth
 ---> Using cache
 ---> 401dc11374f0
Step 3/3 : RUN htpasswd -Bbn testuser testpassword > /auth/htpasswd
 ---> Running in 151df0af2d13
/bin/sh: htpasswd: not found
ERROR: Service 'registry' failed to build: The command '/bin/sh -c htpasswd -Bbn testuser testpassword > /auth/htpasswd' returned a non-zero code: 127
```
