### ISSUE TITLE
Fail to hit breakpoints when opening in browser for Django container with "Python Remote Attach" configuration

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2489]
**OS:** All
**Build Version:** 20201111.4

**Repro Steps:**

1. Open a Python Django project in VS Code -> Add Dockerfile and docker compose files to it -> Set breakpoints for "manage.py" file.
2. Add a new "Python Remote Attach" configuration, example:
```
{
      "name": "Python: Remote Attach",
      "type": "python",
      "request": "attach",
      "port": 5678,
      "host": "localhost",
      "pathMappings": [
         {
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/app"
          } 
      ]
    }
}
```
3. Execute "Compose Up" for docker-compose.yml file -> F5 with "Python: Remote Attach".
4. Navigate to the explorer, right-click the container and "Open in Browser".
5. Check the result.

**Expect:**
Succeed to hit breakpoints.

**Actual:**
Fail to hit breakpoints.

**More Info:**

1. Succeed to hit breakpoints when debugging.
2. This issue doesn't reproduce for Python flask project.

**Comment by bwateratmsft** [comment]
The issue is probably with the path mappings; when I scaffold a remote attach configuration it comes up with this for `"pathMappings"`:
```
"pathMappings": [
    {
        "localRoot": "${workspaceFolder}",
        "remoteRoot": "."
    }
]
```
Depending on how the workspace is structured these may need to be changed. Can you share the shape of your directory tree?

**Comment by v-mengwe** [comment]
The shape of my directory tree:
![Screen Shot 2020-11-13 at 2 30 23 PM](https://user-images.githubusercontent.com/62053665/99036679-18cbfb00-25bd-11eb-8734-1922e861743f.png)
Please get the details from this video ([django.zip](https://github.com/microsoft/vscode-docker/files/5535133/django.zip))

**More Info:**
This is an unstable issue on Mac/Linux, stop automatically when executing F5 for the first time.

**Comment by bwateratmsft** [comment]
That directory structure looks normal to me. It's hard to be sure then why the error. My `docker-compose.debug.yml` file has an argument in the command to use debugpy to launch the app, and instructs it to wait until the debugger connects, so that breakpoints in manage.py can still be hit:

```yml
version: '3.4'

services:
  djangotest2:
    image: djangotest2
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
```

I assume your `docker-compose.debug.yml` looks the same?

**Comment by v-mengwe** [comment]
Yes, my `docker-compose.debug.yml` file is the same as yours.
```
version: '3.4'

services:
  djangoproject:
    image: djangoproject
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
```
