### ISSUE TITLE
Autoformat file on save

### ISSUE THREAD

**Issue by CodingSpiderFox** [microsoft/vscode-docker#2714]
Take the following file

```
version: '3.8'

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch
    ports: 
      - 9200:9200
    - 9300:9300
```

You see the indentation is incorrect. When I save the file it should automatically correct the indentation
