### ISSUE TITLE
Autosuggest popular ports per service

### ISSUE THREAD

**Issue by CodingSpiderFox** [microsoft/vscode-docker#2715]
Given that a user has created this file so far:
```
version: '3.8'

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch
    ports: 
```

pressing enter should automatically open intellisense and suggest to add both the lines:

```
- 9200:9200
- 9300:9300
``` 

Because they are popular port mappings for elasticsearch
