### ISSUE TITLE
docker compose error up

### ISSUE THREAD

**Issue by LucasMarques7** [microsoft/vscode-docker#3116]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.compose.up.subset
Error type: 15
Error Message: Process 'docker-compose -f "docker-compose.yml" config --se...' exited with code 15
Error: (root) Additional property db is not allowed

Version: 1.15.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.58.2
Language: pt-br

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4582672
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:467:12
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by bwateratmsft** [comment]
@LucasMarques7 if you run `docker-compose -f "docker-compose.yml" config --services` in your workspace, what do you see?

**Comment by LucasMarques7** [comment]
$ docker-compose -f "docker-compose.yml" config --services
(root) Additional property db is not allowed

above is my terminal answer.

Below is my code from the compose file:

db:
   image: mariadb:10.4
   ports:
     - '3306:3306'
   environment:
     - MYSQL_ROOT_PASSWORD=GwKdvgQHvQ
     - MYSQL_USER=granodirectdev
     - MYSQL_PASSWORD=GwKdvgQHvQ
     - MYSQL_DATABASE=graodirect

db-test:
   image: mariadb:10.4
   ports:
     - '5000:3306'
   environment:
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_USER=granodirectdev
     - MYSQL_PASSWORD=test
     - MYSQL_DATABASE=graodirect

*Att.*

*Lucas Marques Oliveira*
*034 99977-0677*


Em qui., 5 de ago. de 2021 às 10:56, Brandon Waterloo [MSFT] <
***@***.***> escreveu:

**Comment by bwateratmsft** [comment]
Looks like your compose document is malformed; you're missing the `services` tag at the root. Try this:
```yaml
version: '3.4'

services:
  db:
    image: mariadb:10.4
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=******************
      - MYSQL_USER=granodirectdev
      - MYSQL_PASSWORD=******************
      - MYSQL_DATABASE=graodirect

  db-test:
    image: mariadb:10.4
    ports:
      - '5000:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=******************
      - MYSQL_USER=granodirectdev
      - MYSQL_PASSWORD=******************
      - MYSQL_DATABASE=graodirect
```
