### ISSUE TITLE
Formatting Docker Compose files removes the YAML document end

### ISSUE THREAD

**Issue by ferrarimarco** [microsoft/vscode-docker#3456]
Hi all!

I noticed that formatting a Docker Compose file strips away the [YAML end document marker (`...`)](https://yaml.org/spec/1.2.2/#22-structures). This doesn't happen if you manually set a Docker Compose file as a YAML file, and format it.

Steps to reproduce:

1. Create a Docker Compose file named `compose.yaml` (although any other file name recognized by the [dockercompose language definition](https://github.com/microsoft/vscode/blob/083989d9a2b536a3f29120f1338bfda0983e479c/extensions/yaml/package.json#L22) would work).
2. Ensure that VS Code  recognizes the file `compose.yaml` file as a Docker Compose file (look for the `Compose` language mode in the status bar (bottom right).
3. Paste the following content in the file:
    ```yaml
    ---
    services:
      test-service-1:
    ...
    ```
4. Save the file.
5. Format the file (if you don't have "Format on Save" enabled).

The resulting, formatted file is:

```yaml
---
services:
  test-service-1:
```

While I was expecting:

```yaml
---
services:
  test-service-1:
...
```

Is this behavior something I can configure? Or is it a bug?

Thanks!
