### ISSUE TITLE
YAML anchors broken by formatting

### ISSUE THREAD

**Issue by justinbowes** [microsoft/vscode-docker#3953]
[YAML fragments are supported in docker-compose.yaml.](https://docs.docker.com/compose/compose-file/10-fragments/)

The following minimal example has its anchor (at x-anchor) broken when formatted:

```yaml
version: "3.5"

x-anchor: &anchor
  FOO: bar

services:
  example:
    image: alpine
```

I would expect the compose formatter to not insert newlines that break supported syntax.
