### ISSUE TITLE
Error if the required variable is not specified

### ISSUE THREAD

**Issue by Wintreist** [microsoft/vscode-docker#4402]
_compose.yaml_
```
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?error}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_INITDB_WALDIR=${POSTGRES_INITDB_WALDIR}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
```
All variables are specified in the .env file, except for POSTGRES_PASSWORD.
the .env file is located in the same directory as compose.yaml.
If, with the Docker extension installed, click on compose.bml right-click and select "Select services", then:
`2024-10-21 20:40:15.591 [info] Error: Process exited with code 15`
Maybe you could add in future updates the ability to set the value of variables when launching the service through the Vs code dialog box, and then suggest the past value of the variable at startup?
