### ISSUE TITLE
!reset / !override / … not supported by scheme

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode-docker#4411]
Type: <b>Bug</b>

The !reset / !override tags are not supported and highlighted as errors.

Extension version: 1.29.3
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.42GB free)|
|Process Argv|--folder-uri file:///d%3A/Profiles/anrdaemon/Documents/hk/invapi-php|
|Screen Reader|no|
|VM|0%|
</details>

Example compose file:

```
services:
  nginx:
    ports: !override
      - '127.0.0.1:8080:80'
    build:
      args:
        RELEASE_VERSION: dev
        ENV: dev
        CONF: devenv.conf
    volumes:
      - "./app:/opt/app/app"
      - "./build/nginx/config.js:/opt/app/app/panel/config.js"
  php-fpm:
    build:
      target: devenv
    links: !reset []
    volumes:
      - '.:/opt/app'
      - './build/php-fpm/config.php:/opt/app/config.php'
    extra_hosts:
      - "host.docker.internal:192.168.1.11"
  rabbitmq: !reset null
```

![Image](https://github.com/user-attachments/assets/01c0c510-efa9-4791-abd0-95ed7fc46f48)
